import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next";
import Navbar from "./shared/Navbar";
import { CartProvider } from "./shared/CartContext";
import Sessionwrap from "./shared/Sessionwrap"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "e-commerce",
  description: "Generated by Armaan",
  verification:{google:"Z5fbni8TsY7aYavCtUCsDABQwWvGNLzj0KYcC_gUNlE", },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Sessionwrap> 
          <CartProvider>
            <Navbar/>
            {children}
          </CartProvider>
        </Sessionwrap>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
